### ISSUE TITLE
Not an issue - but wanted to thank you for this excellent work!

### ISSUE THREAD

**Issue by mbwmbw1337** [danielrolls/nix-install#16]
Not an issue - but I wanted to thank you for this excellent work! 

I have been looking for something like his for awhile, so thank you for spending the time on it!

**Comment by danielrolls** [comment]
Try commenting out
```
- name: Remove Installed nix files
  file:
    state: absent
    path: /nix
  become: true
```
and see what happens. The installer may complain. If it works raise an issue and we can add an option to keep or blow away `/nix`. If not it's the installer from upstream that could use a feature request. 

It's great to hear this is being used. This cheered me up after an eventful week. Cheers!
